---
services:
    mysqldb:
      container_name: mysqldb
      image: manikanta1106/bloodbank:db
      ports:
        - "3306:3306"

    application:
      container_name: mycont
      image: manikanta1106/bloodbank:app
      ports:
        - "1212:80"
      depends_on:
        - mysqldb
      
    
